name: Caller Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      some_input: "Hello from caller workflow"
