name: Reusable Workflow

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Input was ${{ inputs.some_input }}"
